services:

  backend:
    build:
      context: ./backend
    container_name: ticket-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ticketdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: ticket-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticketdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend-react:
    build:
      context: ./frontend-react
    container_name: ticket-react
    ports:
      - "3000:3000"
    depends_on:
      - backend

  frontend-angular:
    build:
      context: ./frontend-angular
    container_name: ticket-angular
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres_data:
